/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpiPayment {
    id: bigint;
    status: UpiPaymentStatus;
    hours: bigint;
    sessionType: string;
    upiTransactionId: string;
    accessCode?: string;
    fullName: string;
    pricePerHour: bigint;
    email: string;
    uniqueCode?: string;
    totalAmount: bigint;
    phone: string;
    courseName: string;
}
export interface UserProfile {
    name: string;
    accessCode?: string;
    email: string;
    uniqueCode?: string;
    phone: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type PaymentResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface Attendance {
    id: bigint;
    status: AttendanceStatus;
    studentPrincipal: Principal;
    markedAt: bigint;
    sessionId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ApproveResult = {
    __kind__: "ok";
    ok: {
        accessCode: string;
        fullName: string;
        uniqueCode: string;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type UpiPaymentStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: string;
} | {
    __kind__: "rejected";
    rejected: string | null;
};
export interface AttendanceSummary {
    presentCount: bigint;
    totalSessions: bigint;
    absentCount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Material {
    id: bigint;
    title: string;
    studentPrincipal: Principal;
    fileData?: Uint8Array;
    description?: string;
    fileLink?: string;
    relatedCourse: string;
    uploadedAt: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Session {
    id: bigint;
    topic?: string;
    meetLink: string;
    date: string;
    createdAt: bigint;
    time: string;
    durationHours: bigint;
    studentPrincipal: Principal;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type RejectResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Student {
    principal: Principal;
    paymentStatus: {
        __kind__: "upi";
        upi: UpiPaymentStatus;
    } | {
        __kind__: "stripe";
        stripe: StripeSessionStatus;
    };
    hours: bigint;
    sessionType: string;
    fullName: string;
    isActive: boolean;
    email: string;
    enrollmentDate: bigint;
    phone: string;
    course: string;
    transactionId: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum AttendanceStatus {
    present = "present",
    absent = "absent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMaterial(studentPrincipal: Principal, title: string, description: string | null, fileData: Uint8Array | null, fileLink: string | null, relatedCourse: string): Promise<bigint>;
    addProduct(product: ShoppingItem): Promise<void>;
    addSession(studentPrincipal: Principal, date: string, time: string, durationHours: bigint, meetLink: string, topic: string | null): Promise<bigint>;
    approveUpiPayment(paymentId: bigint, uniqueCode: string): Promise<ApproveResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteMaterial(materialId: bigint): Promise<void>;
    deleteProduct(productName: string): Promise<void>;
    deleteSession(sessionId: bigint): Promise<void>;
    findByEmailQuery(email: string): Promise<UpiPayment | null>;
    findUpiPaymentByAccessCode(code: string): Promise<UpiPayment | null>;
    finishStudentRegistration(fullName: string, email: string, phone: string, course: string, sessionType: string, hours: bigint, paymentType: {
        __kind__: "upi";
        upi: UpiPaymentStatus;
    } | {
        __kind__: "stripe";
        stripe: StripeSessionStatus;
    }, transactionId: string): Promise<void>;
    getAllPayments(): Promise<Array<UpiPayment>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllUpiPaymentsByEmail(email: string): Promise<Array<UpiPayment>>;
    getAttendanceForStudent(studentPrincipal: Principal): Promise<Array<Attendance>>;
    getAttendanceSummary(studentPrincipal: Principal): Promise<AttendanceSummary>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMaterialsForStudent(studentPrincipal: Principal): Promise<Array<Material>>;
    getMyEnrollment(): Promise<Student | null>;
    getPendingPayments(): Promise<Array<UpiPayment>>;
    getProducts(): Promise<Array<ShoppingItem>>;
    getSessionsForStudent(studentPrincipal: Principal): Promise<Array<Session>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUpiPaymentStatus(paymentId: bigint): Promise<UpiPaymentStatus | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markAttendance(studentPrincipal: Principal, sessionId: bigint, status: AttendanceStatus): Promise<bigint>;
    rejectUpiPayment(paymentId: bigint, rejectionNote: string | null): Promise<RejectResult>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    studentFindByEmail(email: string): Promise<UpiPayment | null>;
    submitUpiPayment(courseName: string, sessionType: string, pricePerHour: bigint, hours: bigint, totalAmount: bigint, upiTransactionId: string, fullName: string, email: string, phone: string): Promise<PaymentResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateProduct(product: ShoppingItem): Promise<void>;
    updateStudent(principal: Principal, fullName: string, email: string, phone: string, course: string, sessionType: string, hours: bigint, paymentStatus: {
        __kind__: "upi";
        upi: UpiPaymentStatus;
    } | {
        __kind__: "stripe";
        stripe: StripeSessionStatus;
    }, transactionId: string, enrollmentDate: bigint, isActive: boolean): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, ApproveResult as _ApproveResult, Attendance as _Attendance, AttendanceStatus as _AttendanceStatus, Material as _Material, PaymentResult as _PaymentResult, RejectResult as _RejectResult, Session as _Session, StripeSessionStatus as _StripeSessionStatus, Student as _Student, UpiPayment as _UpiPayment, UpiPaymentStatus as _UpiPaymentStatus, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMaterial(arg0: Principal, arg1: string, arg2: string | null, arg3: Uint8Array | null, arg4: string | null, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaterial(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaterial(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async addProduct(arg0: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async addSession(arg0: Principal, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSession(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSession(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async approveUpiPayment(arg0: bigint, arg1: string): Promise<ApproveResult> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUpiPayment(arg0, arg1);
                return from_candid_ApproveResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUpiPayment(arg0, arg1);
            return from_candid_ApproveResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaterial(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSession(arg0);
            return result;
        }
    }
    async findByEmailQuery(arg0: string): Promise<UpiPayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findByEmailQuery(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findByEmailQuery(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async findUpiPaymentByAccessCode(arg0: string): Promise<UpiPayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findUpiPaymentByAccessCode(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUpiPaymentByAccessCode(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async finishStudentRegistration(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: {
        __kind__: "upi";
        upi: UpiPaymentStatus;
    } | {
        __kind__: "stripe";
        stripe: StripeSessionStatus;
    }, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finishStudentRegistration(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_variant_n20(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishStudentRegistration(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_variant_n20(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async getAllPayments(): Promise<Array<UpiPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUpiPaymentsByEmail(arg0: string): Promise<Array<UpiPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUpiPaymentsByEmail(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUpiPaymentsByEmail(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceForStudent(arg0: Principal): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceForStudent(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceForStudent(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceSummary(arg0: Principal): Promise<AttendanceSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceSummary(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterialsForStudent(arg0: Principal): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialsForStudent(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialsForStudent(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEnrollment(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnrollment();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnrollment();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPayments(): Promise<Array<UpiPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPayments();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPayments();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<ShoppingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getSessionsForStudent(arg0: Principal): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionsForStudent(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionsForStudent(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpiPaymentStatus(arg0: bigint): Promise<UpiPaymentStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpiPaymentStatus(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpiPaymentStatus(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAttendance(arg0: Principal, arg1: bigint, arg2: AttendanceStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n58(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n58(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async rejectUpiPayment(arg0: bigint, arg1: string | null): Promise<RejectResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectUpiPayment(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_RejectResult_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectUpiPayment(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_RejectResult_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async studentFindByEmail(arg0: string): Promise<UpiPayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.studentFindByEmail(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.studentFindByEmail(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitUpiPayment(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: string): Promise<PaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitUpiPayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_PaymentResult_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitUpiPayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_PaymentResult_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateProduct(arg0: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async updateStudent(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: {
        __kind__: "upi";
        upi: UpiPaymentStatus;
    } | {
        __kind__: "stripe";
        stripe: StripeSessionStatus;
    }, arg8: string, arg9: bigint, arg10: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_variant_n20(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_variant_n20(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_ApproveResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApproveResult): ApproveResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Attendance_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Material_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Material): Material {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentResult_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentResult): PaymentResult {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_RejectResult_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RejectResult): RejectResult {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UpiPaymentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpiPaymentStatus): UpiPaymentStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UpiPayment_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpiPayment): UpiPayment {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UpiPayment]): UpiPayment | null {
    return value.length === 0 ? null : from_candid_UpiPayment_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UpiPaymentStatus]): UpiPaymentStatus | null {
    return value.length === 0 ? null : from_candid_UpiPaymentStatus_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _UpiPaymentStatus;
    hours: bigint;
    sessionType: string;
    upiTransactionId: string;
    accessCode: [] | [string];
    fullName: string;
    pricePerHour: bigint;
    email: string;
    uniqueCode: [] | [string];
    totalAmount: bigint;
    phone: string;
    courseName: string;
}): {
    id: bigint;
    status: UpiPaymentStatus;
    hours: bigint;
    sessionType: string;
    upiTransactionId: string;
    accessCode?: string;
    fullName: string;
    pricePerHour: bigint;
    email: string;
    uniqueCode?: string;
    totalAmount: bigint;
    phone: string;
    courseName: string;
} {
    return {
        id: value.id,
        status: from_candid_UpiPaymentStatus_n17(_uploadFile, _downloadFile, value.status),
        hours: value.hours,
        sessionType: value.sessionType,
        upiTransactionId: value.upiTransactionId,
        accessCode: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.accessCode)),
        fullName: value.fullName,
        pricePerHour: value.pricePerHour,
        email: value.email,
        uniqueCode: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.uniqueCode)),
        totalAmount: value.totalAmount,
        phone: value.phone,
        courseName: value.courseName
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    paymentStatus: {
        upi: _UpiPaymentStatus;
    } | {
        stripe: _StripeSessionStatus;
    };
    hours: bigint;
    sessionType: string;
    fullName: string;
    isActive: boolean;
    email: string;
    enrollmentDate: bigint;
    phone: string;
    course: string;
    transactionId: string;
}): {
    principal: Principal;
    paymentStatus: {
        __kind__: "upi";
        upi: UpiPaymentStatus;
    } | {
        __kind__: "stripe";
        stripe: StripeSessionStatus;
    };
    hours: bigint;
    sessionType: string;
    fullName: string;
    isActive: boolean;
    email: string;
    enrollmentDate: bigint;
    phone: string;
    course: string;
    transactionId: string;
} {
    return {
        principal: value.principal,
        paymentStatus: from_candid_variant_n30(_uploadFile, _downloadFile, value.paymentStatus),
        hours: value.hours,
        sessionType: value.sessionType,
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        enrollmentDate: value.enrollmentDate,
        phone: value.phone,
        course: value.course,
        transactionId: value.transactionId
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AttendanceStatus;
    studentPrincipal: Principal;
    markedAt: bigint;
    sessionId: bigint;
}): {
    id: bigint;
    status: AttendanceStatus;
    studentPrincipal: Principal;
    markedAt: bigint;
    sessionId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n37(_uploadFile, _downloadFile, value.status),
        studentPrincipal: value.studentPrincipal,
        markedAt: value.markedAt,
        sessionId: value.sessionId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    accessCode: [] | [string];
    email: string;
    uniqueCode: [] | [string];
    phone: string;
}): {
    name: string;
    accessCode?: string;
    email: string;
    uniqueCode?: string;
    phone: string;
} {
    return {
        name: value.name,
        accessCode: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.accessCode)),
        email: value.email,
        uniqueCode: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.uniqueCode)),
        phone: value.phone
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    studentPrincipal: Principal;
    fileData: [] | [Uint8Array];
    description: [] | [string];
    fileLink: [] | [string];
    relatedCourse: string;
    uploadedAt: bigint;
}): {
    id: bigint;
    title: string;
    studentPrincipal: Principal;
    fileData?: Uint8Array;
    description?: string;
    fileLink?: string;
    relatedCourse: string;
    uploadedAt: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        studentPrincipal: value.studentPrincipal,
        fileData: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.fileData)),
        description: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.description)),
        fileLink: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.fileLink)),
        relatedCourse: value.relatedCourse,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: [] | [string];
    meetLink: string;
    date: string;
    createdAt: bigint;
    time: string;
    durationHours: bigint;
    studentPrincipal: Principal;
}): {
    id: bigint;
    topic?: string;
    meetLink: string;
    date: string;
    createdAt: bigint;
    time: string;
    durationHours: bigint;
    studentPrincipal: Principal;
} {
    return {
        id: value.id,
        topic: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.topic)),
        meetLink: value.meetLink,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        durationHours: value.durationHours,
        studentPrincipal: value.studentPrincipal
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n56(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        accessCode: string;
        fullName: string;
        uniqueCode: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        accessCode: string;
        fullName: string;
        uniqueCode: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: string;
} | {
    rejected: [] | [string];
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: string;
} | {
    __kind__: "rejected";
    rejected: string | null;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "approved" in value ? {
        __kind__: "approved",
        approved: value.approved
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: from_candid_opt_n19(_uploadFile, _downloadFile, value.rejected)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: _UpiPaymentStatus;
} | {
    stripe: _StripeSessionStatus;
}): {
    __kind__: "upi";
    upi: UpiPaymentStatus;
} | {
    __kind__: "stripe";
    stripe: StripeSessionStatus;
} {
    return "upi" in value ? {
        __kind__: "upi",
        upi: from_candid_UpiPaymentStatus_n17(_uploadFile, _downloadFile, value.upi)
    } : "stripe" in value ? {
        __kind__: "stripe",
        stripe: from_candid_StripeSessionStatus_n31(_uploadFile, _downloadFile, value.stripe)
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n33(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UpiPayment>): Array<UpiPayment> {
    return value.map((x)=>from_candid_UpiPayment_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Material>): Array<Material> {
    return value.map((x)=>from_candid_Material_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n54(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_StripeSessionStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StripeSessionStatus): _StripeSessionStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UpiPaymentStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpiPaymentStatus): _UpiPaymentStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Uint8Array | null): [] | [Uint8Array] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal?: string;
    response: string;
}): {
    userPrincipal: [] | [string];
    response: string;
} {
    return {
        userPrincipal: value.userPrincipal ? candid_some(value.userPrincipal) : candid_none(),
        response: value.response
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    accessCode?: string;
    email: string;
    uniqueCode?: string;
    phone: string;
}): {
    name: string;
    accessCode: [] | [string];
    email: string;
    uniqueCode: [] | [string];
    phone: string;
} {
    return {
        name: value.name,
        accessCode: value.accessCode ? candid_some(value.accessCode) : candid_none(),
        email: value.email,
        uniqueCode: value.uniqueCode ? candid_some(value.uniqueCode) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "upi";
    upi: UpiPaymentStatus;
} | {
    __kind__: "stripe";
    stripe: StripeSessionStatus;
}): {
    upi: _UpiPaymentStatus;
} | {
    stripe: _StripeSessionStatus;
} {
    return value.__kind__ === "upi" ? {
        upi: to_candid_UpiPaymentStatus_n24(_uploadFile, _downloadFile, value.upi)
    } : value.__kind__ === "stripe" ? {
        stripe: to_candid_StripeSessionStatus_n21(_uploadFile, _downloadFile, value.stripe)
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
}): {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
} {
    return value.__kind__ === "completed" ? {
        completed: to_candid_record_n23(_uploadFile, _downloadFile, value.completed)
    } : value.__kind__ === "failed" ? {
        failed: value.failed
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: string;
} | {
    __kind__: "rejected";
    rejected: string | null;
}): {
    pending: null;
} | {
    approved: string;
} | {
    rejected: [] | [string];
} {
    return value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "approved" ? {
        approved: value.approved
    } : value.__kind__ === "rejected" ? {
        rejected: value.rejected ? candid_some(value.rejected) : candid_none()
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
