/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ApproveResult = {
    'ok' : { 'accessCode' : string, 'fullName' : string, 'uniqueCode' : string }
  } |
  { 'err' : string };
export interface Attendance {
  'id' : bigint,
  'status' : AttendanceStatus,
  'studentPrincipal' : Principal,
  'markedAt' : bigint,
  'sessionId' : bigint,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface AttendanceSummary {
  'presentCount' : bigint,
  'totalSessions' : bigint,
  'absentCount' : bigint,
}
export interface Material {
  'id' : bigint,
  'title' : string,
  'studentPrincipal' : Principal,
  'fileData' : [] | [Uint8Array],
  'description' : [] | [string],
  'fileLink' : [] | [string],
  'relatedCourse' : string,
  'uploadedAt' : bigint,
}
export type PaymentResult = { 'ok' : bigint } |
  { 'err' : string };
export type RejectResult = { 'ok' : null } |
  { 'err' : string };
export interface Session {
  'id' : bigint,
  'topic' : [] | [string],
  'meetLink' : string,
  'date' : string,
  'createdAt' : bigint,
  'time' : string,
  'durationHours' : bigint,
  'studentPrincipal' : Principal,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpiPayment {
  'id' : bigint,
  'status' : UpiPaymentStatus,
  'hours' : bigint,
  'sessionType' : string,
  'upiTransactionId' : string,
  'accessCode' : [] | [string],
  'fullName' : string,
  'pricePerHour' : bigint,
  'email' : string,
  'uniqueCode' : [] | [string],
  'totalAmount' : bigint,
  'phone' : string,
  'courseName' : string,
}
export type UpiPaymentStatus = { 'pending' : null } |
  { 'approved' : string } |
  { 'rejected' : [] | [string] };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'accessCode' : [] | [string],
  'email' : string,
  'uniqueCode' : [] | [string],
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMaterial' : ActorMethod<
    [
      Principal,
      string,
      [] | [string],
      [] | [Uint8Array],
      [] | [string],
      string,
    ],
    bigint
  >,
  'addProduct' : ActorMethod<[ShoppingItem], undefined>,
  'addSession' : ActorMethod<
    [Principal, string, string, bigint, string, [] | [string]],
    bigint
  >,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'approveUpiPayment' : ActorMethod<[bigint, string], ApproveResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteMaterial' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteSession' : ActorMethod<[bigint], undefined>,
  'findByEmailQuery' : ActorMethod<[string], [] | [UpiPayment]>,
  'findUpiPaymentByAccessCode' : ActorMethod<[string], [] | [UpiPayment]>,
  'getAllPayments' : ActorMethod<[], Array<UpiPayment>>,
  'getAllUpiPaymentsByEmail' : ActorMethod<[string], Array<UpiPayment>>,
  'getAttendanceForStudent' : ActorMethod<[Principal], Array<Attendance>>,
  'getAttendanceSummary' : ActorMethod<[Principal], AttendanceSummary>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaterialsForStudent' : ActorMethod<[Principal], Array<Material>>,
  'getPendingPayments' : ActorMethod<[], Array<UpiPayment>>,
  'getProducts' : ActorMethod<[], Array<ShoppingItem>>,
  'getSessionsForStudent' : ActorMethod<[Principal], Array<Session>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUpiPaymentStatus' : ActorMethod<[bigint], [] | [UpiPaymentStatus]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markAttendance' : ActorMethod<[Principal, bigint, AttendanceStatus], bigint>,
  'rejectUpiPayment' : ActorMethod<[bigint, [] | [string]], RejectResult>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'studentFindByEmail' : ActorMethod<[string], [] | [UpiPayment]>,
  'submitUpiPayment' : ActorMethod<
    [string, string, bigint, bigint, bigint, string, string, string, string],
    PaymentResult
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProduct' : ActorMethod<[ShoppingItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];